export const ActionType = {
    FETCH_DATA_PENDING: 'FETCH_DATA_PENDING',
    FETCH_DATA_FULFILLED: 'FETCH_DATA_FULFILLED',
    FETCH_DATA_REJECTED:'FETCH_DATA_REJECTED',
    FILTER_PRODUCTS_DATA:'FILTER_PRODUCTS_DATA'
};